// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var _;

  _ = require('lodash');

  module.exports = function(PaginationService) {
    return function(data) {
      var current, end, offset, start;
      if (_.isEmpty(data)) {
        return data;
      }
      offset = PaginationService.getItemsPerPage();
      current = PaginationService.getCurrentPage();
      start = current * offset;
      end = start + offset;
      return data.slice(start, end);
    };
  };

}).call(this);
