// Generated by CoffeeScript 1.10.0
(function() {
  var _;

  _ = require('lodash');

  module.exports = [
    'PaginationService', function(PaginationService) {
      return {
        restrict: 'A',
        transclude: true,
        controller: 'PaginationCtrl',
        scope: {
          changed: '=changed',
          itemsperpage: '=itemsperpage',
          totalitems: '=totalitems'
        },
        templateUrl: 'directives/pagination.html',
        link: function($scope, $elem, $attr) {
          var callBack;
          callBack = function() {
            if (_.isFunction($scope.changed)) {
              return $scope.changed(PaginationService.getCurrentPage(), PaginationService.getPageCount());
            }
          };
          $scope.range = function() {
            return PaginationService.setRange();
          };
          $scope.nextPageDisabled = function() {
            if (PaginationService.getCurrentPage() === PaginationService.getPageCount()) {
              return "disabled";
            } else {
              return "";
            }
          };
          $scope.prevPageDisabled = function() {
            if (PaginationService.getCurrentPage() === 0) {
              return "disabled";
            } else {
              return "";
            }
          };
          $scope.nextPage = function() {
            PaginationService.nextPage();
            return callBack();
          };
          $scope.prevPage = function() {
            PaginationService.prevPage();
            return callBack();
          };
          $scope.setActive = function(i) {
            if (i === PaginationService.getCurrentPage()) {
              return "active";
            } else {
              return "";
            }
          };
          return $scope.setPage = function(i) {
            PaginationService.setPage(i);
            return callBack();
          };
        }
      };
    }
  ];

}).call(this);
