// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var _;

  _ = require('lodash');

  module.exports = [
    '$scope', 'PaginationService', function($scope, PaginationService) {
      $scope.showPagination = false;
      if (!(_.isUndefined($scope.itemsperpage) || $scope.itemsperpage <= 0)) {
        PaginationService.setItemsPerPage($scope.itemsperpage);
      }
      return $scope.$watch('totalitems', function(totalItems) {
        if (!_.isUndefined(totalItems)) {
          PaginationService.setPageCount(totalItems);
          $scope.showPagination = PaginationService.getPageCount() > 0;
          if (_.isFunction($scope.changed)) {
            return $scope.changed(PaginationService.getCurrentPage(), PaginationService.getPageCount());
          }
        }
      });
    }
  ];

}).call(this);
